"""create documents table

Revision ID: 204ca57273de
Revises: 874c7b86684d
Create Date: 2026-08-21 19:08:09.079004

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '204ca57273de'
down_revision: Union[str, Sequence[str], None] = '874c7b86684d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
