"""add operational maintenance tables

Revision ID: 7aa1d9c94908
Revises: d5435e467860
Create Date: 2026-08-24 02:00:31.486929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7aa1d9c94908"
down_revision: Union[str, Sequence[str], None] = "d5435e467860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("asset_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "asset_code", name="uq_assets_tenant_asset_code"),
    )
    op.create_index(op.f("ix_assets_asset_code"), "assets", ["asset_code"], unique=False)
    op.create_index(op.f("ix_assets_tenant_id"), "assets", ["tenant_id"], unique=False)
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_date", sa.Date(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("technician", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_records_asset_id"), "maintenance_records", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_records_maintenance_date"),
        "maintenance_records",
        ["maintenance_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_records_tenant_id"), "maintenance_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "maintenance_tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("issue", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_tickets_asset_id"), "maintenance_tickets", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_tickets_tenant_id"), "maintenance_tickets", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenance_tickets_tenant_id"), table_name="maintenance_tickets")
    op.drop_index(op.f("ix_maintenance_tickets_asset_id"), table_name="maintenance_tickets")
    op.drop_table("maintenance_tickets")
    op.drop_index(op.f("ix_maintenance_records_tenant_id"), table_name="maintenance_records")
    op.drop_index(op.f("ix_maintenance_records_maintenance_date"), table_name="maintenance_records")
    op.drop_index(op.f("ix_maintenance_records_asset_id"), table_name="maintenance_records")
    op.drop_table("maintenance_records")
    op.drop_index(op.f("ix_assets_tenant_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_code"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
