"""create documents table

Revision ID: d5435e467860
Revises: 204ca57273de
Create Date: 2026-08-21 19:08:16.699822

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd5435e467860'
down_revision: Union[str, Sequence[str], None] = '204ca57273de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
